pool: noni_pool
trigger: none 
jobs:
  - job: terraform 
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          
          Write-Host "Hello World"